### ISSUE TITLE
Node engine needs to be updated

### ISSUE THREAD

**Issue by tomowens3** [NodeRedis/node-redis-parser#21] opened 2016-11-08 02:51 UTC
The major version should be bumped or at least the node engine  version should be updated from >=0.10.0 to >0.12. This would warn us poor souls that continue to support apps that run old but still maintained NodeJS versions that we could have an issue and fail the installation in strict mode.

For those that are interested:
node_redis@>=2.6.2  + NodeJS 0.12.15 causes a memory leak that also seems to max out the CPU of the instance.

**Comment by BridgeAR** [comment] 2016-11-08 21:27
@tomowens3 can you elaborate what commands you used and how you found the memory leak? I am not aware of such a leak and if there is indeed a memory leak in combination with NodeJS 0.12.15 are you certain there is none in combination with newer NodeJS versions?

**Comment by tomowens3** [comment] 2016-11-09 06:17
We resolved the issue by setting the redis-parser dependency version in the app's shrinkwrap.json back to 2.0.4. 

The commands used are just the basics ( incr, set, get, setex, del, expire, mget and multi/exec )

**Comment by BridgeAR** [comment] 2016-11-18 15:58
I guess the issue is now resolved with v.2.2.0?

**Comment by BridgeAR** [comment] 2016-11-20 16:37
If this is still the case, please reopen.

**Closed by BridgeAR** 2016-11-20 16:37 UTC
